# Hydra stuff
hydra:
  output_subdir: null
  run:
    dir: "."

defaults:
  - _self_
  - override hydra/job_logging: disabled

# Extra logging information
logger_name: "learn_labeler"
trial: "3"

### Dataset
dataset: "mixed"
## Setting
# Generalized setting (or not)
fixed_db: true
no_replacement: true
sim_imbalance: false
# N-way, K-shot setting
n_ways: 5
n_shots: 5
n_queries: 15

### Model config
## Specify model to use
label_recovery_model: "resnet12"
train_model: "resnet12"
feat_dim: 640
lam: 0.001
# Loading pretrained model(s)
pretrained_labeler: false
pretrained_centroids: false
pretrained_model: false
# Centroid arguments
K: 400
std_factor: 3.5

## Training
batch_size: 128 #only used at labeling, else set to 1
train_db_size: 2800
test_db_size: 1000
num_workers: 4
epochs: 50
# If we use n * lam instead of lam
normalize_lam: false
# For validation accuracy
val_n_ways: 5
val_n_shots: 5

# Data augmentation
data_aug: false
rotate_aug: false
sup_rotate_aug: true # for after labeling the samples
sup_data_aug: true # for after labeling the samples

# Optimization
SGD: true
learning_rate: 0.05
lr_decay_epochs: "35,43"
lr_decay_rate: 0.1
weight_decay: 5e-4
momentum: 0.9

## Testing
test_C: 1.0
use_bias: true
is_norm: true

### Auxiliary settings
progress: true
