# Hydra stuff
hydra:
  output_subdir: null
  run:
    dir: "."

defaults:
  - _self_
  - override hydra/job_logging: disabled

# Extra logging information
logger_name: "sup_baseline"
trial: "5"

### Dataset
dataset: "mixed"
# N-way, K-shot setting
n_ways: 5
n_shots: 5
n_queries: 15

### Model config
## Specify model to use
model: "resnet12"
feat_dim: 640
lam: 0.001
# Loading pretrained model
pretrained_model: false

## Training
batch_size: 64
test_db_size: 1000
num_workers: 4
epochs: 50
# For validation accuracy
val_n_ways: 5
val_n_shots: 5

# Data augmentation
data_aug: true
rotate_aug: true

# Optimization
SGD: true
learning_rate: 0.05
lr_decay_epochs: "35,43"
lr_decay_rate: 0.1
weight_decay: 5e-4
momentum: 0.9

## Testing
test_C: 1.0
use_bias: true
is_norm: true

### Auxiliary settings
progress: true
