# Hydra stuff
hydra:
  output_subdir: null
  run:
    dir: "."

defaults:
  - _self_
  - override hydra/job_logging: disabled

# Extra logging information
logger_name: "sup_proto"
trial: "5"

### Dataset
dataset: "metadataset"
# All dataset: (train+val+test) aircraft, cub, dtd, fungi, imagenet, omniglot, quickdraw, vgg (val+test) mscoco, (test) traffic_sign
#datasets: "aircraft,cub,dtd,fungi,imagenet,omniglot,quickdraw,vgg,mscoco,traffic_sign"
# N-way, K-shot setting
n_ways: 5
n_shots: 5
n_queries: 15

### Model config
## Specify model to use
model: "resnet18"
feat_dim: 640
lam: 0.001
# Loading pretrained model
pretrained_model: false

## Training
batch_size: 64
test_db_size: 1000
num_workers: 4
epoch_size: 5000
epochs: 20
# For validation accuracy
val_n_ways: 20
val_n_shots: 20

# Data augmentation
data_aug: true
rotate_aug: false

# Optimization
SGD: true
learning_rate: 0.05
lr_decay_epochs: "12,16"
#  "35,42"
lr_decay_rate: 0.1
weight_decay: 5e-4
momentum: 0.9

## Testing
test_C: 1.0
use_bias: true
is_norm: true

### Auxiliary settings
progress: true
